- hosts: localhost

  vars:

    udev:
      rules_dir: /etc/udev/rules.d

    trackpoint:
      device: /sys/devices/platform/i8042/serio1/serio2
      attr:
        speed: 97
        sensitivity: 210

  tasks:

    - tags:
        - configure
        - configure.trackpoint

      block:

        - name: install trackpoint udev rule
          become: true
          template:
            src: udev-rules/trackpoint.rules.j2
            dest: '{{ udev.rules_dir }}/trackpoint.rules'
