- hosts: local
  vars:
    touchpad_xorg:
      options:
        Buttons: 3
        ScrollMethod: twofinger
        NaturalScrolling: 'true'
        ButtonMapping: '1 0 3'

    trackpoint_udev:

      device: /sys/devices/platform/i8042/serio1/serio2
      attr:
        speed: 97
        sensitivity: 210

    trackpoint_xorg:
      priority: 60
      options:
        Buttons: '3'
        # Disable middle button paste
        ButtonMapping: '1 0 3'

        # libinput acceleration
        AccelProfile: "adaptive"
        AccelSpeed: '1'

    input_device_configs:
      stick_udev:
        present: false
        src: udev-rules/trackpoint.rules.j2
        dest: '{{ udev.rules_dir }}/70-trackpoint.rules'
      stick_xorg:
        present: false
        src: xorg-conf/trackpoint.conf.j2
        dest: '{{ xorg.conf_dir }}/50-trackpoint-joar.conf'
      pad_xorg:
        src: xorg-conf/touchpad.conf.j2
        dest: '{{ xorg.conf_dir }}/70-touchpad-joar.conf'
        present: true

    pointingstick_hwdb:
      event_device: /sys/class/input/event8
      sensitivity: 255
      const_accel: '1.0'

    pointingstick_hwdb_config:
      src: hwdb/trackpoint.hwdb.j2
      dest: '{{ udev.hwdb_dir }}/99-pointingstick-x1-tablet-joar.hwdb'

  tasks:
    - tags:
        - input-devices

      block:

        - include: tasks/template-or-absent.yaml
          become: true
          vars:
            item_: '{{ item }}'
          with_items: '{{ input_device_configs.values()|list }}'

    - tags:
        - input-devices
        - hwdb
        - pointingstick

      block:

        - name: add X1 Yoga HWDB entry
          become: true
          template:
            src: '{{ pointingstick_hwdb_config.src }}'
            dest: '{{ pointingstick_hwdb_config.dest }}'
          register: _pointingstick_hwdb_entry

        - when: _pointingstick_hwdb_entry|changed
          block:

            - name: reload hwdb
              become: true
              command: systemd-hwdb update

            - name: trigger event device
              become: true
              command: 'udevadm trigger {{ pointingstick_hwdb.event_device }}'
