- hosts: local

  vars:
    local_bin: /home/joar/.local/bin

    udev:
      rules_dir: /etc/udev/rules.d

    packages_path: /home/joar/src

    helm_base: '{{ packages_path }}/helm-{{ helm_version }}'
    helm_bin: helm
    helm_version: 2.4.2
    helm_archive_name: 'helm-v{{ helm_version }}-linux-amd64.tar.gz'
    # The path of the helm binary inside the archive
    helm_archive_bin: linux-amd64/helm
    helm_archive_url_base: https://kubernetes-helm.storage.googleapis.com

    trackpoint:
      device: /sys/devices/platform/i8042/serio1/serio2
      attr:
        speed: 97
        sensitivity: 210

  tasks:

    - tags:
        - configure
        - configure.trackpoint

      block:

        - name: install trackpoint udev rule
          become: true
          template:
            src: udev-rules/trackpoint.rules.j2
            dest: '{{ udev.rules_dir }}/trackpoint.rules'

    - tags:
        - helm

      block:

        - file:
            path: '{{ helm_base }}'
            state: directory

        - get_url:
            url: '{{ helm_archive_url_base }}/{{ helm_archive_name }}'
            dest: '{{ helm_base }}/{{ helm_archive_name }}'

        - unarchive:
            list_files: true
            src: '{{ helm_base }}/{{ helm_archive_name }}'
            dest: '{{ helm_base }}'
          register: _helm_unarchive

        - name: find helm binary in unpacked archive
          fail: msg='helm binary {{ helm_archive_bin }} not found in archive'
          when: "helm_archive_bin not in _helm_unarchive['files']"

        - name: >
            link {{ local_bin }}/{{ helm_bin }}
            ⇒ {{ helm_base }}/{{ helm_archive_bin }}
          file:
            path: '{{ local_bin }}/{{ helm_bin }}'
            src: '{{ helm_base }}/{{ helm_archive_bin }}'
            state: link
